name: Build Site
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'local'
      - '.idea/**'
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Check out site submodule
      - name: Check out submodule
        run: |
          git submodule init site
          git submodule update site

      # Set up Java environment for the next steps
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Validate wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # Build application
      - name: Build
        run: ./gradlew kobwebExport -PkobwebReuseServer=false -PkobwebEnv=DEV -PkobwebRunLayout=KOBWEB -PkobwebBuildTarget=RELEASE -PkobwebExportLayout=STATIC

      # Stop kobweb server
      - name: Stop Server
        run: ./gradlew kobwebStop

      # If main branch update, deploy to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site/build/docs # The folder the action should deploy.
          clean-exclude: 404.html
