name: Build Site
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'local'
      - '.idea/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      - run: |
          git submodule init site
          git submodule update site


      # Set up Java environment for the next steps
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Validate wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # Install Kobweb
      - name: Install Kobweb
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with: # Grab a specific tag
          repo: varabyte/kobweb
          tag: cli-v0.9.10
          cache: enable # not expected to speed up installation
          
      # Export Site
      - name: Export Site
        run: kobweb export --layout static --mode dumb # "dumb" prevents java awt display error
        working-directory: ./site

      # If main branch update, deploy to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site/build/docs # The folder the action should deploy.
          clean-exclude: 404.html
